MySQL:
  host: localhost
  port: 3306
  user: user
  password: password
  database: db
  table-prefix: "parkour_"
  database-update-timer-minutes: 30


hologram:
  height: 1.0
  parkour:
    start:
      - "&6Start"
    end:
      - "&b&lEnd"

parkour:
  max-fall-distance: 3
  plate-type: HEAVY_WEIGHTED_PRESSURE_PLATE