MySQL:
  host: localhost
  port: 3306
  user: user
  password: password
  database: db
  table-prefix: "parkour_"
  database-update-timer-minutes: 30

gui:
  top-players:
    head-displayName: '&e#${pos} &a${name}'
    lore:
      - "&d${time}"
  player-info:

hologram:
  line-height: 0.5
  parkour:
    start:
      - "&6Start"
    end:
      - "&b&lEnd"
    checkpoint:
      - "&bCheckpoint #${id}"
  top:
    base:
      - "&e&l${parkourName}"
      - "&fYour position is &b#${userPosition} &f- with time &e${time}"
    top_players: "&a#${id} &b${name} - &e${time}"


parkour:
  max-fall-distance: 3
  plate-type: HEAVY_WEIGHTED_PRESSURE_PLATE