MySQL:
  host: localhost
  port: 3306
  user: user
  password: password
  database: db
  table-prefix: "parkour_"
  database-update-timer-minutes: 30

gui:
  top-players:
    head-displayName: '&e#${pos} &a${name}'
    lore:
      - "&d${time}"
  player-info:

hologram:
  line-height: 0.5
  top:
    interval-seconds: 5

scoreboard:
  update-interval-ticks: 10

parkour:
  max-fall-distance: 3
  plate-type: HEAVY_WEIGHTED_PRESSURE_PLATE