main: io.github.invvk.seniorparkour.SeniorParkour
version: 1.0.0
name: SeniorParkour
author: Invvk
api-version: 1.16
libraries:
  - io.github.rysefoxx.inventory:RyseInventory-Plugin:1.5.7

commands:
  parkour: